---
apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: default
  labels:
    app: product-api
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: product-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-api
  namespace: default
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: product-api
  namespace: default
spec:
  protocol: "http"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
  namespace: default
data:
  config: |
    {
      "db_connection": "host=product-api-db port=5432 user=postgres password=password dbname=products sslmode=disable",
      "bind_address": ":9090",
      "metrics_address": ":9103"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: default
  labels:
    app: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: product-api
      volumes:
        - name: config
          configMap:
            name: db-configmap
            items:
              - key: config
                path: conf.json
      containers:
        - name: product-api
          image: hashicorpdemoapp/product-api:v0.0.22
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
            - containerPort: 9103
          env:
            - name: "CONFIG_FILE"
              value: "/config/conf.json"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 30
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
