kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.24.0
  extraPortMappings:
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 8501
    hostPort: 8501
    protocol: TCP
  - containerPort: 8502
    hostPort: 8502
    protocol: TCP
  - containerPort: 8443
    hostPort: 8443
    protocol: TCP
